version: '3'
services:
  mongodb:
    image: mongo:5.0.1
    container_name: order-mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb_data: